apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-redis
  labels:
    app: todo-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-redis
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: todo-redis
    spec:
      containers:
        - name: redis
          image: redislabs/rejson:latest
          ports:
            - containerPort: 6379